
[project]
name = "zuspec-dataclasses"
version = "0.0.1"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.entry-points."flake8.extension"]
ZDC = "zuspec.dataclasses.flake8_zdc_struct:plugin_factory"

[tool.mypy]
mypy_path = "src"
plugins = ["zuspec.dataclasses.mypy.plugin"]
show_column_numbers = true
show_error_end = true

[tool.setuptools.package-data]
"zuspec.dataclasses" = [
    "llms.txt",
    "py.typed"
]
